spring:
  application:
    name: spring-cloud-ribbon

server:
  port: 8003

ping-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9001,localhost:9002
    ServerListRefreshInterval: 15000