server:
  port: 8004
spring:
  cloud:
    server:
      git:
        uri: https://github.com/wmfsystem/tcc-fafiman.git
        searchPaths: configs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/