spring:
  profiles: default
server:
  port: 8000
eureka:
  instance:
    hostname: 127.0.0.1
    preferIpAddress: true
    ipAddress: ${external.ip:${spring.cloud.client.ipAddress:localhost}}
  client:
    registerWithEureka: false
    fetchRegistry: false
#  server:
#    enableSelfPreservation: false

  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
