spring:
  application:
    name: EurekaServer

server:
  port: 8000
  display-name: EurekaServer

eureka:
  instance:
    hostname: localhost
  server:
      enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka