server:
  port: 9001
spring:
  cloud:
    server:
      git:
        uri: https://github.com/wmfsystem/tcc
        searchPaths: configs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/