---
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8000/eureka/
     
# Zuul-proxied services can be found by calling /services/subject, /services/verb, etc.
zuul:
  prefix: /services   
