server:
  port: 8004
spring:
  cloud:9001
    server:
      git:
        uri: https://github.com/wmfsystem/tcc-fafiman
        searchPaths: configs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/