spring:
  application:
    name: EurekaClient
server:
  port: 9000
  display-name: EurekaClient
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    preferIpAddress: true

