spring:
  application:
    name: EurekaClient
server:
  port: 8001
  display-name: EurekaClient
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      statusPageUrl: http://${eureka.instance.hostname}:${server.port}/info
      healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/health
      homePageUrl: http://${eureka.instance.hostname}:${server.port}/
      hostname: localhost

