spring:
  application:
    name: HystrixServer
server:
  port: 8001
  display-name: HystrixServer
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
