spring:
  application:
    name: HystrixServer
eureka:
  instance:
    metadata-map:
      management.port: ${management.port:8081}
turbine:
  aggregator:
    clusterConfig: SYSTEM,USER
  appConfig: customers,stores,ui,admin
  clusterNameExpression: metadata['cluster']