spring:
  application:
    name: turbine

server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

turbine:
  clusterNameExpression: new String("default")
  appConfig: EUREKACLIENT
  combineHostPort: true